# Generated by Django 6.0.7 on 2026-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='appointment',
            name='unique_booked_doctor_slot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('doctor', 'start_time'), name='unique_booked_doctor_slot', violation_error_code='unique_booked_doctor_slot'),
        ),
    ]
